// React/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { DocumentEditorContainerComponent, Toolbar } from '@syncfusion/ej2-react-documenteditor';
import * as ReactDOM from 'react-dom';
DocumentEditorContainerComponent.Inject(Toolbar);
class App extends Component {

  hosturl = 'https://document.syncfusion.com/web-services/docx-editor/api/documenteditor/';
container;
  onDocumentChange() {
    let proxy = this;
    //To detect the device
    let isMobileDevice = /Android|Windows Phone|webOS/i.test(navigator.userAgent);

    if (isMobileDevice) {
      proxy.container.restrictEditing = true;
      setTimeout(() => {
        proxy.container.documentEditor.fitPage("FitPageWidth");
      }, 50);
    }
    else {
      proxy.container.restrictEditing = false;
    }
  }


  render() {
    return (
      <div className="App">
        <DocumentEditorContainerComponent id="container" ref={(scope) => { this.container = scope; }} style={{ 'height': '590px' }} enableToolbar={true} documentChange={this.onDocumentChange.bind(this)} serviceUrl={this.hosturl} height={'590px'}/>
      </div>
    );
  }
}

export default App;

// Vue/src/App.vue
<template>
  <div id="app">
    <ejs-documenteditorcontainer
      ref="container"
      height="590px"
      :serviceUrl="serviceUrl"
      :enableToolbar="true"
      :documentChange="onDocumentChange">
    </ejs-documenteditorcontainer>
  </div>
</template>

<script>
import {
  DocumentEditorContainerPlugin,
  DocumentEditorContainerComponent,
  Toolbar
} from '@syncfusion/ej2-vue-documenteditor';

export default {
  data() {
    return {
      serviceUrl: 'https://document.syncfusion.com/web-services/docx-editor/api/documenteditor/'
    };
  },
  provide: {
    // Inject required modules
    DocumentEditorContainer: [Toolbar]
  },
  methods: {
    onDocumentChange: function () {
      // To detect the device
      let isMobileDevice = /Android|Windows Phone|webOS/i.test(navigator.userAgent);

      if (isMobileDevice) {
        this.$refs.container.ej2Instances.restrictEditing = true;
        setTimeout(() => {
          this.$refs.container.ej2Instances.documentEditor.fitPage('FitPageWidth');
        }, 50);
      } else {
        this.$refs.container.ej2Instances.restrictEditing = false;
      }
    }
  }
};
</script>

<style>
@import '../node_modules/@syncfusion/ej2-base/styles/material.css';
@import '../node_modules/@syncfusion/ej2-buttons/styles/material.css';
@import '../node_modules/@syncfusion/ej2-inputs/styles/material.css';
@import '../node_modules/@syncfusion/ej2-popups/styles/material.css';
@import '../node_modules/@syncfusion/ej2-lists/styles/material.css';
@import '../node_modules/@syncfusion/ej2-navigations/styles/material.css';
@import '../node_modules/@syncfusion/ej2-splitbuttons/styles/material.css';
@import '../node_modules/@syncfusion/ej2-dropdowns/styles/material.css';
@import '../node_modules/@syncfusion/ej2-vue-documenteditor/styles/material.css';
</style>
